POS/POS.Web/Controllers/AjaxController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using POS.Repo;

namespace POS.Web.Controllers
{
    public class AjaxController : Controller
    {
        // GET: Ajax
        public JsonResult GetProvince()
        {
            return Json(MstProvinceRepo.Get(), JsonRequestBehavior.AllowGet);
        }


        public JsonResult GetRegion(int provinceId)
        {
            return Json(MstRegionRepo.GetByProvinsi(provinceId), JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetDistrict(int regionId)
        {
            return Json(MstDistrictRepo.GetByRegion(regionId), JsonRequestBehavior.AllowGet);
        }
    }
}

POS/POS.Web/Controllers/MstSupplierController.cs
using POS.Repo;
using POS.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace POS.Web.Controllers
{
    public class MstSupplierController : Controller
    {
        // Index : MstSupplier
        public ActionResult Index()
        {
            return View(MstSupplierRepo.Get());
        }

        // List : MstSupplier
        public ActionResult List()
        {
            return PartialView("_List", MstSupplierRepo.Get());
        }

        // search
        public ActionResult Search(string keySearch)
        {
            return PartialView("_List", MstSupplierRepo.Get(keySearch));
        }

        public ActionResult Add()
        {
            ViewBag.ListProvince = new SelectList(MstProvinceRepo.Get(), "id", "name");
            ViewBag.ListRegion = new SelectList(String.Empty, "", "");
            ViewBag.ListDistrict = new SelectList(String.Empty, "", "");
            return PartialView("_Add");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(MstSupplierViewModel model)
        {
            if (ModelState.IsValid)
            {
                if (MstSupplierRepo.Insert(model))
                {
                    return Json(new { success = true, message = "Data berhasil disimpan" });
                }
                else
                {
                    return Json(new { success = false, message = "Data gagal disimpan" });
                }
            }
            ViewBag.ListProvince = new SelectList(MstProvinceRepo.Get(), "id", "name");
            ViewBag.ListRegion = new SelectList(String.Empty, "", "");
            ViewBag.ListDistrict = new SelectList(String.Empty, "", "");
            return PartialView("_Add", model);
        }

        public ActionResult Edit(int id)
        {
            ViewBag.ListProvince = new SelectList(MstProvinceRepo.Get(), "id", "name");
            ViewBag.ListRegion = new SelectList(MstRegionRepo.Get(), "id", "name");
            ViewBag.ListDistrict = new SelectList(MstDistrictRepo.Get(), "id", "name");
            return PartialView("_Edit", MstSupplierRepo.Get(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(MstSupplierViewModel model)
        {
            if (ModelState.IsValid)
            {
                if (MstSupplierRepo.Update(model))
                {
                    return Json(new { success = true, message = "Data berhasil disimpan" });
                }
                else
                {
                    return Json(new { success = false, message = "Data gagal disimpan" });
                }
            }
            ViewBag.ListProvince = new SelectList(MstProvinceRepo.Get(), "id", "name");
            ViewBag.ListRegion = new SelectList(MstRegionRepo.Get(), "id", "name");
            ViewBag.ListDistrict = new SelectList(MstDistrictRepo.Get(), "id", "name");
            return PartialView("_Edit", model);
        }
    }
}

POS/POS.Web/Views/MstSupplier/Index.cshtml
@model IEnumerable<POS.ViewModel.MstSupplierViewModel>

@{
    ViewBag.Title = "Index supplier";
}

<div class="box box-info">

    <div class="box-header">
        <div class="form-group">
            <h3 class="box-title">&nbsp;suppliers</h3>

        </div>
        <div class="form-group">
            <div class="box-tools">

                <div class="input-group input-group-sm" style="width: 250px;">
                    <input type="text" id="txt-search" name="txt-search" class="form-control" placeholder="Search">
                    <div class="input-group-btn">
                        <button type="button" id="btn-search" class="btn btn-default"><i class="fa fa-search"></i></button>
                        <button type="button" class="btn btn-info" id="btn-add"><i class="fa fa-plus"></i></button>
                    </div>
                </div>

            </div>
        </div>

    </div>
    <div class="box-body" id="list-data">
        @Html.Partial("_List", Model)
    </div>
</div>

<div id="modal-form" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Modal title</h4>
            </div>
            <div class="modal-body">

            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
@section Scripts{
    <script type="text/javascript">
    // fungsi modal
    function ajaxModal(vUrl, vData, vTitle) {
        $.ajax({
            url: vUrl,
            data: vData,
            type: 'get',
            dataType: 'html',
            success: function (result) {
                $(".modal-title").html(vTitle);
                $(".modal-body").html(result);
                $("#modal-form").modal('show');
            }
        });
    }

    //method load data
    function loadData(url, data) {
        $.ajax({
            url: url,
            data: data,
            type: 'get',
            dataType: 'html',
            success: function (data) {
                $("#list-data").html(data);
            }
        });
    }

    $(document).ready(function () {
        // menekan button create
        $("#btn-add").on("click", function () {
            ajaxModal('@Url.Action("Add","MstSupplier")', null, "supplier Detail - Add");
        });

        // menekan button edit
        $("#list-data").on("click", ".btn-edit", function () {
            // mendeklarasikan id yang dipilih
            var vId = $(this).val();
            // memanggil method ajaxModel diatas
            ajaxModal('@Url.Action("Edit","MstSupplier")', { id: vId }, "supplier Detail - Edit");
        });

        // event form submit
        $("#modal-form").on("submit", "#form-supplier", function () {
            var action = $(this).attr('action');
            var formData = $(this).serialize();
            $.ajax({
                url: action,
                type: 'post',
                dataType: 'json',
                data: formData,
                success: function (rdata) {
                    if (rdata.success) {
                        // menyembunyikan modal
                        $("#modal-form").modal("hide");
                        // memanggil method load data
                        loadData('@Url.Action("List","MstSupplier")', null);
                    } else {
                        $(".modal-body").html(rdata);
                        $("#modal-form").modal("show");
                    }
                }
            });
            return false;
        });

        // search
        $("#btn-search").on("click", function () {
            var url = '@Url.Action("Search", "MstSupplier")';
            var data = { keySearch: $('#txt-search').val() };
            loadData(url, data);
        });

        //provinsi di pilih
        $("#modal-form").on("change", "#province_id", function () {
            var vId = $(this).val();
            $.ajax({
                url: '@Url.Action("GetRegion", "Ajax")',
                data: { provinceId: vId },
                type: 'get',
                dataType: 'json',
                success: function (result) {
                    $("#modal-form").find("#region_id").empty();
                    $("#modal-form").find("#region_id").append('<option>Region</option>');
                    $.each(result, function (index, item) {
                        $("#modal-form").find("#region_id").append('<option value="' + item.id + '">' + item.name + '</option>');
                    });
                }
            });
        });

        // Kota di pilih
        $("#modal-form").on("change", "#region_id", function () {
            var vId = $(this).val();
            $.ajax({
                url: '@Url.Action("GetDistrict", "Ajax")',
                data: { regionId: vId },
                type: 'get',
                dataType: 'json',
                success: function (result) {
                    $("#modal-form").find("#district_id").empty();
                    $("#modal-form").find("#district_id").append('<option>District</option>');
                    $.each(result, function (index, item) {
                        $("#modal-form").find("#district_id").append('<option value="' + item.id + '">' + item.name + '</option>');
                    });
                }
            });
        });
    });
    </script>
}

POS/POS.Web/Views/MstSupplier/_Add.cshtml
@model POS.ViewModel.MstSupplierViewModel

@using (Html.BeginForm("Add", "MstSupplier", FormMethod.Post, new { @id = "form-supplier" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        
        <div class="form-group">
            <div class="col-md-12">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" , @placeholder="Name"} })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-12">
                @Html.EditorFor(model => model.address, new { htmlAttributes = new { @class = "form-control", @placeholder = "Address" } })
                @Html.ValidationMessageFor(model => model.address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-4">
                @Html.DropDownListFor(model => model.province_id, (IEnumerable<SelectListItem>)ViewBag.ListProvince, "Province", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.province_id, "", new { @class = "text-danger" })
            </div>

            <div class="col-md-4">
                @Html.DropDownListFor(model => model.region_id, (IEnumerable<SelectListItem>)ViewBag.ListRegion, "Region", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.region_id, "", new { @class = "text-danger" })
            </div>

            <div class="col-md-4">
                @Html.DropDownListFor(model => model.district_id, (IEnumerable<SelectListItem>)ViewBag.ListDistrict, "District", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.district_id, "", new { @class = "text-danger" })
            </div>


        </div>

        <div class="form-group">


            <div class="col-md-4">
                @Html.EditorFor(model => model.postal_code, new { htmlAttributes = new { @class = "form-control", @placeholder = "Postal Code" } })
                @Html.ValidationMessageFor(model => model.postal_code, "", new { @class = "text-danger" })
            </div>

            <div class="col-md-4">
                @Html.EditorFor(model => model.phone, new { htmlAttributes = new { @class = "form-control", @placeholder = "Phone" } })
                @Html.ValidationMessageFor(model => model.phone, "", new { @class = "text-danger" })
            </div>

            <div class="col-md-4">
                @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control", @placeholder = "Email" } })
                @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
            </div>


        </div>

        <!--Hapus
        <div class="form-group">

            <div class="col-md-12">
                @Html.EditorFor(model => model.active, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.active, "", new { @class = "text-danger" })
            </div>

        </div>
        
        
        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.province_id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.province_id, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.province_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.region_id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.region_id, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.region_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.district_id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.district_id, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.district_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.postal_code, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.postal_code, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.postal_code, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.active, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.active, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.active, "", new { @class = "text-danger" })
            </div>
        </div>
            -->

        <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">
                Cancel
            </button>
            <button type="submit" class="btn btn-primary pull-right">
                Save
            </button>
        </div>
    </div>
}

POS/POS.Web/Views/MstSupplier/_Edit.cshtml
@model POS.ViewModel.MstSupplierViewModel

@using (Html.BeginForm("Edit", "MstSupplier", FormMethod.Post, new { @id = "form-supplier" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)


        <div class="form-group">
            
            <div class="col-md-12">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
           
        </div>

        <div class="form-group">
            
            <div class="col-md-12">
                @Html.EditorFor(model => model.address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.address, "", new { @class = "text-danger" })
            </div>
            
        </div>

        <div class="form-group">


            <div class="col-md-4">
                @Html.DropDownListFor(model => model.province_id, (IEnumerable<SelectListItem>)ViewBag.ListProvince, "Province", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.province_id, "", new { @class = "text-danger" })
            </div>

            <div class="col-md-4">
                @Html.DropDownListFor(model => model.region_id, (IEnumerable<SelectListItem>)ViewBag.ListRegion, "Region", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.region_id, "", new { @class = "text-danger" })
            </div>

            <div class="col-md-4">
                @Html.DropDownListFor(model => model.district_id, (IEnumerable<SelectListItem>)ViewBag.ListDistrict, "District", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.district_id, "", new { @class = "text-danger" })
            </div>


        </div>

        <div class="form-group">
            
                
                <div class="col-md-4">
                    @Html.EditorFor(model => model.postal_code, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.postal_code, "", new { @class = "text-danger" })
                </div>
                
                <div class="col-md-4">
                    @Html.EditorFor(model => model.phone, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.phone, "", new { @class = "text-danger" })
                </div>
                
                <div class="col-md-4">
                    @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
                </div>
                
           
        </div>

        <!--Hapus aja
        <div class="form-group">
            
            <div class="col-md-12">
                @Html.EditorFor(model => model.active, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.active, "", new { @class = "text-danger" })
            </div>

        </div>
            -->

        <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">
                Cancel
            </button>
            <button type="submit" class="btn btn-primary pull-right">
                Save
            </button>
        </div>
    </div>
}

POS/POS.Web/Views/MstSupplier/_List.cshtml
@model IEnumerable<POS.ViewModel.MstSupplierViewModel>

<table class="table table-bordered table-striped">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.phone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.email)
        </th>
        <th> # </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.phone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.email)
            </td>
            <td>
                <button id="btn-edit" class="btn btn-warning btn-xs btn-edit" value="@item.id"><i class="fa fa-edit"></i></button>
            </td>
        </tr>
    }
</table>