POS/POS.Web/Controllers/MstItemController.cs
using POS.Repo;
using POS.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace POS.Web.Controllers
{
    public class MstItemController : Controller
    {
        // GET: MstItem
        public ActionResult Index()
        {
            return View(MstItemRepo.Get());
        }

        public ActionResult Add()
        {
            ViewBag.ListCategory = new SelectList(MstCategoryRepo.Get(),"id","name");
            return PartialView("_Add");
        }

        [HttpPost]
        public ActionResult Add(MstItemViewModel model)
        {
            if (ModelState.IsValid)
            {
                if (MstItemRepo.Insert(model))
                {
                    return Json(new
                    {
                        success = true,
                        message = "Data berhasil disimpan"
                    });
                }
                else
                {
                    return Json(new
                    {
                        success = false,
                        message = "Data gagal disimpan"
                    });
                }
            }
            ViewBag.ListCategory = new SelectList(MstCategoryRepo.Get(), "id", "name");
            return View(model);

        }

        public ActionResult AddVariant()
        {
            return PartialView("_AddVariant");
        }


        public ActionResult Edit(int id)
        {
            MstItemViewModel data = MstItemRepo.Get(id);
            //@ViewBag.ListCategory = new SelectList(MstCategoryRepo.Get(),"id","name");
            return PartialView("_Edit",data);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(MstItemViewModel model)
        {
            if (ModelState.IsValid)
            {
                if (MstItemRepo.Update(model))
                {
                    return Json(new
                    {
                        success = true,
                        messege = "Berhasil simpan"
                    });
                }
                else
                {
                    return Json(new
                    {
                        success = false,
                        messege = "Gagal"
                    });
                }
            }
            return PartialView("_Edit", model);
        }

        public ActionResult List()
        {
            return PartialView("_List", MstItemRepo.Get());
        }

        public ActionResult Detail(int id)
        {
            return PartialView("_Detail", MstItemRepo.Get(id));
        }

    }
}

POS/POS.Web/Controllers/MstOutletController.cs
using POS.Repo;
using POS.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace POS.Web.Controllers
{
    public class MstOutletController : Controller
    {
        // ajax kota
      

        // Index : MstOutlet
        public ActionResult Index()
        {
            return View(MstOutletRepo.Get());
        }

        // List : MstOutlet
        public ActionResult List()
        {
            return PartialView("_List", MstOutletRepo.Get());
        }

        // search
        public ActionResult Search(string keySearch)
        {
            return PartialView("_List", MstOutletRepo.Get(keySearch));
        }

        public ActionResult Add()
        {
            ViewBag.ListProvince = new SelectList(MstProvinceRepo.Get(), "id", "name");
            ViewBag.ListRegion = new SelectList(String.Empty, "", "");
            ViewBag.ListDistrict = new SelectList(String.Empty, "", "");
            return PartialView("_Add");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(MstOutletViewModel model)
        {
            if (ModelState.IsValid)
            {
                if (MstOutletRepo.Insert(model))
                {
                    return Json(new { success = true, message = "Data berhasil disimpan" });
                }
                else
                {
                    return Json(new { success = false, message = "Data gagal disimpan" });
                }
            }
            ViewBag.ListProvince = new SelectList(MstProvinceRepo.Get(), "id", "name");
            ViewBag.ListRegion = new SelectList(String.Empty, "", "");
            ViewBag.ListDistrict = new SelectList(String.Empty, "", "");
            return PartialView("_Add", model);
        }

        public ActionResult Edit(int id)
        {
            ViewBag.ListProvince = new SelectList(MstProvinceRepo.Get(), "id", "name");
            ViewBag.ListRegion = new SelectList(MstRegionRepo.Get(), "id", "name");
            ViewBag.ListDistrict = new SelectList(MstDistrictRepo.Get(), "id", "name");
            return PartialView("_Edit", MstOutletRepo.Get(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(MstOutletViewModel model)
        {
            if (ModelState.IsValid)
            {
                if (MstOutletRepo.Update(model))
                {
                    return Json(new { success = true, message = "Data berhasil disimpan" });
                }
                else
                {
                    return Json(new { success = false, message = "Data gagal disimpan" });
                }
            }
            ViewBag.ListProvince = new SelectList(MstProvinceRepo.Get(), "id", "name");
            ViewBag.ListRegion = new SelectList(MstRegionRepo.Get(), "id", "name");
            ViewBag.ListDistrict = new SelectList(MstDistrictRepo.Get(), "id", "name");
            return PartialView("_Edit", model);
        }
    }
}

POS/POS.Web/Controllers/MstRoleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using POS.Repo;
using POS.ViewModel;

namespace POS.Web.Controllers
{
    public class MstRoleController : Controller
    {
        // GET: MstRole
        public ActionResult Index()
        {
            return View(MstRoleRepo.Get());
        }

        // // list Dosen
        public ActionResult List()
        {
            return PartialView("_List", MstRoleRepo.Get());
        }

        // search
        public ActionResult Search(string keySearch)
        {
            return PartialView("_List", MstRoleRepo.Get(keySearch));
        }

        // Add Data
        public ActionResult Add()
        {
            return PartialView("_Add");
        }
        // Add Data Submit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(MstRoleViewModel model)
        {
            if (ModelState.IsValid)
            {
                if (MstRoleRepo.Insert(model))
                {
                    return Json(new
                    {
                        success = true,
                        message = "Data berhasil disimpan"
                    });
                }
                else
                {
                    return Json(new
                    {
                        success = false,
                        message = "Data gagal disimpan"
                    });
                }
            }
            return PartialView("_Add", model);
        }

        // detail data
        public ActionResult Detail(int id)
        {
            MstRoleViewModel data = MstRoleRepo.Get(id);
            return PartialView("_Detail", data);
        }

        // edit data
        public ActionResult Edit(int id)
        {
            ViewBag.ListUser = new SelectList(MstUserRepo.Get(), "id", "username");
            MstRoleViewModel data = MstRoleRepo.Get(id);
            return PartialView("_Edit", data);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(MstRoleViewModel model)
        {
            ViewBag.ListUser = new SelectList(MstUserRepo.Get(), "id", "username");
            if (ModelState.IsValid)
            {
                if (MstRoleRepo.Update(model))
                {
                    return Json(new
                    {
                        success = true,
                        message = "Simpan Berhasil"
                    });
                }
                else
                {
                    return Json(new
                    {
                        success = false,
                        message = "Simpan Gagal"
                    });
                }
            }
            return PartialView("_Edit", model);
        }

        // delete data
        public ActionResult Delete(int id)
        {
            MstRoleViewModel data = MstRoleRepo.Get(id);
            return PartialView("_Delete", data);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(MstRoleViewModel model)
        {
            if (ModelState.IsValid)
            {
                if (MstRoleRepo.Delete(model))
                {
                    return Json(new
                    {
                        success = true,
                        message = "Simpan Berhasil"
                    });
                }
                else
                {
                    return Json(new
                    {
                        success = false,
                        message = "Simpan Gagal"
                    });
                }
            }
            return PartialView("_Delete", model);
        }

    }



}

POS/POS.Web/Controllers/MstUserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using POS.Repo;
using POS.ViewModel;

namespace POS.Web.Controllers
{
    public class MstUserController : Controller
    {
        // GET: MstUser
        public ActionResult Index()
        {
            return View(MstUserRepo.Get());
        }

        // // list Dosen
        public ActionResult List()
        {
            return PartialView("_List", MstUserRepo.Get());
        }

        // Add Data
        public ActionResult Add()
        {
            return PartialView("_Add");
        }
        // Add Data Submit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(MstUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                if (MstUserRepo.Insert(model))
                {
                    return Json(new
                    {
                        success = true,
                        message = "Data berhasil disimpan"
                    });
                }
                else
                {
                    return Json(new
                    {
                        success = false,
                        message = "Data gagal disimpan"
                    });
                }
            }
            return PartialView("_Add", model);
        }

        // detail data
        public ActionResult Detail(int id)
        {
            MstUserViewModel data = MstUserRepo.Get(id);
            return PartialView("_Detail", data);
        }

        // edit data
        public ActionResult Edit(int id)
        {
            ViewBag.ListRole = new SelectList(MstRoleRepo.Get(), "id", "name");
            MstUserViewModel data = MstUserRepo.Get(id);
            return PartialView("_Edit", data);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(MstUserViewModel model)
        {
            ViewBag.ListRole = new SelectList(MstRoleRepo.Get(), "id", "name");
            if (ModelState.IsValid)
            {
                if (MstUserRepo.Update(model))
                {
                    return Json(new
                    {
                        success = true,
                        message = "Simpan Berhasil"
                    });
                }
                else
                {
                    return Json(new
                    {
                        success = false,
                        message = "Simpan Gagal"
                    });
                }
            }
            return PartialView("_Edit", model);
        }

        // delete data
        public ActionResult Delete(int id)
        {
            MstUserViewModel data = MstUserRepo.Get(id);
            return PartialView("_Delete", data);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(MstUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                if (MstUserRepo.Delete(model))
                {
                    return Json(new
                    {
                        success = true,
                        message = "Simpan Berhasil"
                    });
                }
                else
                {
                    return Json(new
                    {
                        success = false,
                        message = "Simpan Gagal"
                    });
                }
            }
            return PartialView("_Delete", model);
        }
    }
}

POS/POS.Web/Views/Shared/_ControlSidebar.cshtml
<!-- Control Sidebar -->
<aside class="control-sidebar control-sidebar-dark">
    <!-- Create the tabs -->
    <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
        <li><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>
        <li><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li>
    </ul>
    <!-- Tab panes -->
    <div class="tab-content">
        <!-- Home tab content -->
        <div class="tab-pane" id="control-sidebar-home-tab">
            <h3 class="control-sidebar-heading">Recent Activity</h3>
            <ul class="control-sidebar-menu">
                <li>
                    <a href="javascript:void(0)">
                        <i class="menu-icon fa fa-birthday-cake bg-red"></i>
                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Langdon's Birthday</h4>
                            <p>Will be 23 on April 24th</p>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="javascript:void(0)">
                        <i class="menu-icon fa fa-user bg-yellow"></i>
                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Frodo Updated His Profile</h4>
                            <p>New phone +1(800)555-1234</p>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="javascript:void(0)">
                        <i class="menu-icon fa fa-envelope-o bg-light-blue"></i>
                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Nora Joined Mailing List</h4>
                            <p>nora@example.com</p>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="javascript:void(0)">
                        <i class="menu-icon fa fa-file-code-o bg-green"></i>
                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Cron Job 254 Executed</h4>
                            <p>Execution time 5 seconds</p>
                        </div>
                    </a>
                </li>
            </ul>
            <!-- /.control-sidebar-menu -->
            <h3 class="control-sidebar-heading">Tasks Progress</h3>
            <ul class="control-sidebar-menu">
                <li>
                    <a href="javascript:void(0)">
                        <h4 class="control-sidebar-subheading">
                            Custom Template Design
                            <span class="label label-danger pull-right">70%</span>
                        </h4>
                        <div class="progress progress-xxs">
                            <div class="progress-bar progress-bar-danger" style="width: 70%"></div>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="javascript:void(0)">
                        <h4 class="control-sidebar-subheading">
                            Update Resume
                            <span class="label label-success pull-right">95%</span>
                        </h4>
                        <div class="progress progress-xxs">
                            <div class="progress-bar progress-bar-success" style="width: 95%"></div>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="javascript:void(0)">
                        <h4 class="control-sidebar-subheading">
                            Laravel Integration
                            <span class="label label-warning pull-right">50%</span>
                        </h4>
                        <div class="progress progress-xxs">
                            <div class="progress-bar progress-bar-warning" style="width: 50%"></div>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="javascript:void(0)">
                        <h4 class="control-sidebar-subheading">
                            Back End Framework
                            <span class="label label-primary pull-right">68%</span>
                        </h4>
                        <div class="progress progress-xxs">
                            <div class="progress-bar progress-bar-primary" style="width: 68%"></div>
                        </div>
                    </a>
                </li>
            </ul>
            <!-- /.control-sidebar-menu -->
        </div>
        <!-- /.tab-pane -->
        <!-- Stats tab content -->
        <div class="tab-pane" id="control-sidebar-stats-tab">Stats Tab Content</div>
        <!-- /.tab-pane -->
        <!-- Settings tab content -->
        <div class="tab-pane" id="control-sidebar-settings-tab">
            <form method="post">
                <h3 class="control-sidebar-heading">General Settings</h3>
                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Report panel usage
                        <input type="checkbox" class="pull-right" checked>
                    </label>
                    <p>
                        Some information about this general settings option
                    </p>
                </div>
                <!-- /.form-group -->
                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Allow mail redirect
                        <input type="checkbox" class="pull-right" checked>
                    </label>
                    <p>
                        Other sets of options are available
                    </p>
                </div>
                <!-- /.form-group -->
                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Expose author name in posts
                        <input type="checkbox" class="pull-right" checked>
                    </label>
                    <p>
                        Allow the user to show his name in blog posts
                    </p>
                </div>
                <!-- /.form-group -->
                <h3 class="control-sidebar-heading">Chat Settings</h3>
                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Show me as online
                        <input type="checkbox" class="pull-right" checked>
                    </label>
                </div>
                <!-- /.form-group -->
                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Turn off notifications
                        <input type="checkbox" class="pull-right">
                    </label>
                </div>
                <!-- /.form-group -->
                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Delete chat history
                        <a href="javascript:void(0)" class="text-red pull-right"><i class="fa fa-trash-o"></i></a>
                    </label>
                </div>
                <!-- /.form-group -->
            </form>
        </div>
        <!-- /.tab-pane -->
    </div>
</aside>
<!-- /.control-sidebar -->
<!-- Add the sidebar's background. This div must be placed
     immediately after the control sidebar -->
<div class="control-sidebar-bg"></div>

POS/POS.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - POS</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>

<body class="hold-transition skin-yellow sidebar-mini">
    <div class="wrapper">
        <!--Load halaman _Header.cshtml-->
        @Html.Partial("_Header")

        <!-- Left side column. contains the logo and sidebar -->
        @Html.Partial("_Sidebar")

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <section class="content-header">
                <h1>
                    Dashboard
                    <small>Control panel</small>
                </h1>
                <ol class="breadcrumb">
                    <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                    <li class="active">Dashboard</li>
                </ol>
            </section>

            <!-- Main content -->
            <section class="content">
                <div class="row">
                    <div class="col-md-12">
                        @RenderBody()
                    </div>
                </div>
            </section>
        </div>

        <!-- /.content-wrapper -->
        <footer class="main-footer">
            <div class="pull-right hidden-xs">
                <b>Version</b> 2.3.8
            </div>
            <strong>Copyright &copy; @DateTime.Now.Year <a href="http://almsaeedstudio.com">Almsaeed Studio</a>.</strong> All rights
            reserved.
        </footer>

        <!--Load Control sidebar-->
        @Html.Partial("_ControlSidebar")
    </div>
    @Scripts.Render("~/bundles/jquery")
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>
        $.widget.bridge('uibutton', $.ui.button);
    </script>
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

POS/POS.Web/Views/Shared/_Sidebar.cshtml
 <!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <!-- Sidebar user panel -->
        <div class="user-panel">
            <div class="pull-left image">
                <img src="~/img/user2-160x160.jpg" class="img-circle" alt="User Image">
            </div>
            <div class="pull-left info">
                <p>Alexander Pierce</p>
                <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
        </div>
        <!-- search form -->
        <form action="#" method="get" class="sidebar-form">
            <div class="input-group">
                <input type="text" name="q" class="form-control" placeholder="Search...">
                <span class="input-group-btn">
                    <button type="submit" name="search" id="search-btn" class="btn btn-flat">
                        <i class="fa fa-search"></i>
                    </button>
                </span>
            </div>
        </form>
        <!-- /.search form -->
        <!-- sidebar menu: : style can be found in sidebar.less -->
        <ul class="sidebar-menu">
            <li class="header">MAIN NAVIGATION</li>
            <li class="active treeview">
                <a href="#">
                    <i class="fa fa-dashboard"></i> <span>Master Data</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="@Url.Action("Index","MstCategory")"><i class="fa fa-circle-o"></i> Category</a></li>
                    <li><a href="@Url.Action("Index","MstCustomer")"><i class="fa fa-circle-o"></i> Customer</a></li>
                    <li><a href="@Url.Action("Index","MstDistrict")"><i class="fa fa-circle-o"></i> District</a></li>
                    <li><a href="@Url.Action("Index","MstRegion")"><i class="fa fa-circle-o"></i> Region</a></li>
                    <li><a href="@Url.Action("Index","MstProvince")"><i class="fa fa-circle-o"></i> Province</a></li>
                    <li><a href="@Url.Action("Index","MstEmployee")"><i class="fa fa-circle-o"></i> Employee</a></li>
                    <li><a href="@Url.Action("Index","MstItem")"><i class="fa fa-circle-o"></i> Item</a></li>
                    <li><a href="@Url.Action("Index","MstItemVariant")"><i class="fa fa-circle-o"></i> Item Variant</a></li>
                    <li><a href="@Url.Action("Index","MstInventory")"><i class="fa fa-circle-o"></i> Inventory</a></li>
                    <li><a href="@Url.Action("Index","MstOutlet")"><i class="fa fa-circle-o"></i> Outlet</a></li>
                    <li><a href="@Url.Action("Index","MstSupplier")"><i class="fa fa-circle-o"></i> Supplier</a></li>
                    <li><a href="@Url.Action("Index","MstRole")"><i class="fa fa-circle-o"></i> Role</a></li>
                    <li><a href="@Url.Action("Index","MstUser")"><i class="fa fa-circle-o"></i> User</a></li>
                </ul>
            </li>
            <li class="active treeview">
                <a href="#">
                    <i class="fa fa-dashboard"></i> <span>Transaction</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="@Url.Action("Index","EmployeeOutlet")"><i class="fa fa-circle-o"></i> Employee Outlet</a></li>
                </ul>
            </li>
        </ul>
    </section>
    <!-- /.sidebar -->
</aside>