POS/POS.Web/Controllers/MstEmployeeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using POS.Model;
using POS.ViewModel;
using POS.Repo;

namespace POS.Web.Controllers
{
    public class MstEmployeeController : Controller
    {
        // GET: MstProvince
        public ActionResult Index()
        {
            return View(MstEmployeeRepo.Get());
        }

        public ActionResult List()
        {
            return PartialView("_List", MstEmployeeRepo.Get());
        }


        // search
        public ActionResult Search(string keySearch)
        {
            return PartialView("_List", MstEmployeeRepo.Get(keySearch));
        }

        public ActionResult AddOutlet()
        {
            ViewBag.ListOutlet = new SelectList(MstOutletRepo.Get(), "id", "name");

            return PartialView("_AddOutlet");
        }
        
        public ActionResult Add()
        {
            ViewBag.listRole = new SelectList(MstRoleRepo.Get(), "id", "name");
            ViewBag.listOutlet = new SelectList(MstOutletRepo.Get(), "id", "name");

            return PartialView("_Add");
        }


        // Add Data Submit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(MstEmployeeViewModel model)
        {
            if (ModelState.IsValid)
            {
                if (MstEmployeeRepo.Insert(model))
                {
                    return Json(new
                    {
                        success = true,
                        message = "Berhasil simpan"
                    });
                }
                else
                {
                    return Json(new
                    {
                        success = false,
                        message = "Gagal simpan"
                    });
                }
            }

            ViewBag.listRole = new SelectList(MstRoleRepo.Get(), "id", "name");
            ViewBag.listOutlet = new SelectList(MstOutletRepo.Get(), "id", "name");

            return PartialView("_Add", model);
        }

        // detail data
        public ActionResult Detail(int id)
        {
            MstEmployeeViewModel data = MstEmployeeRepo.Get(id);
            return PartialView("_Detail", data);
        }

        // edit data
        public ActionResult Edit(int id)
        {
            //ViewBag.ListUser = new SelectList(MstUserRepo.Get(), "id", "username");
            MstEmployeeViewModel data = MstEmployeeRepo.Get(id);
            ViewBag.listRole = new SelectList(MstRoleRepo.Get(), "id", "name");
            ViewBag.listOutlet = new SelectList(MstOutletRepo.Get(), "id", "name");

            return PartialView("_Edit", data);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(MstEmployeeViewModel model)
        {
            //ViewBag.ListUser = new SelectList(MstUserRepo.Get(), "id", "username");
            if (ModelState.IsValid)
            {
                if (MstEmployeeRepo.Update(model))
                {
                    return Json(new
                    {
                        success = true,
                        message = "Simpan Berhasil"
                    });
                }
                else
                {
                    return Json(new
                    {
                        success = false,
                        message = "Simpan Gagal"
                    });
                }
            }

            ViewBag.listRole = new SelectList(MstRoleRepo.Get(), "id", "name");
            ViewBag.listOutlet = new SelectList(MstOutletRepo.Get(), "id", "name");
            return PartialView("_Edit", model);
        }


        // delete data
        public ActionResult Delete(int id)
        {
            MstEmployeeViewModel data = MstEmployeeRepo.Get(id);
            return PartialView("_Delete", data);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(MstEmployeeViewModel model)
        {
            if (ModelState.IsValid)
            {
                if (MstEmployeeRepo.Delete(model))
                {
                    return Json(new
                    {
                        success = true,
                        message = "Simpan Berhasil"
                    });
                }
                else
                {
                    return Json(new
                    {
                        success = false,
                        message = "Simpan Gagal"
                    });
                }
            }
            return PartialView("_Delete", model);
        }

    }
}

POS/POS.Web/Views/MstEmployee/Index.cshtml
@model IEnumerable<POS.ViewModel.MstEmployeeViewModel>

@{
    ViewBag.Title = "Index";
}
<div class="box box-info">
    <div class="box-header">
        <h3 class="box-title">Employee List</h3>

        <div class="box-tools">
            <div class="input-group input-group-sm" style="width: 250px;">
                <input type="text" id="txt-search" name="txt-search" class="form-control pull-right" placeholder="Search">
                <div class="input-group-btn">
                    <button type="button" id="btn-search" class="btn btn-default"><i class="fa fa-search"></i></button>
                    <button type="button" id="btn-add" class="btn btn-info"><i class="fa fa-plus"></i></button>
                </div>
            </div>
        </div>
    </div>

    <div class="box-body" id="list-data">
        @Html.Partial("_List", Model)
    </div>

</div>

<!-- modals JQuery-->
<div id="modal-form" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Modal title</h4>
            </div>
            <div class="modal-body">
                <p>One fine body&hellip;</p>
            </div>
        </div>
    </div>
</div>

<!-- modals JQuery-->
<div id="modal-outlet" class="modal fade" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Modal title</h4>
            </div>
            <div class="modal-body">
                <p>One fine body&hellip;</p>
            </div>
        </div>
    </div>
</div>

@section Scripts{

    <script type="text/javascript">
        function ajaxModal(vUrl, vData, vTitle) {
            $.ajax({
                url: vUrl,
                data: vData,
                type: 'get',
                dataType: 'html',
                success: function (result) {
                    $("#modal-form .modal-title").html(vTitle);
                    $("#modal-form .modal-body").html(result);
                    $("#modal-form").modal('show');
                }
            });
        }

        //Load data
        function loadData() {
            $.ajax({
                url: '@Url.Action("List", "MstEmployee")',
                type: 'get',
                dataType: 'html',
                success: function (data) {
                    $("#list-data").html(data);
                }
            });
        }

        $(document).ready(function () {

            $("#modal-form").on("click", "#chkAccount", function () {
                if ($(this).is(":checked")) {
                    $("#dvRole").show();
                } else {
                    $("#dvRole").hide();
                }
            });


            //button click Add Variant
            $("#modal-form").on("click", "#btn-add-outlet", function () {
                $.ajax({
                    url: '@Url.Action("AddOutlet", "MstEmployee")',
                    type: 'get',
                    dataType: 'html',
                    success: function (result) {
                        $("#modal-outlet .modal-title").html("Add Outlet");
                        $("#modal-outlet .modal-body").html(result);
                        $("#modal-outlet").modal('show');
                    }
                });
            });

            $("#modal-outlet").on("click", "#btn-pilih-outlet", function () {
                var outletId = $("#modal-outlet #outlet_id").val();
                var outletName = $("#modal-outlet #outlet_id option:selected").text();
                var index = $("#modal-form #list-outlet >tr").length;
                var data = '<tr>' +
                        '<td><input type="text" name="EmployeeOutlet[' + index + '].outlet_id" value="' + outletId + '" class="form-control" /></td>' +
                         '<td>' + outletName  + '</td>' +
                    '</tr>';

                $("#modal-form #list-outlet").append(data);
            });

            // event add
            //$("#btn-add").click(function () {
            $("#btn-add").on("click", function () {
                ajaxModal('@Url.Action("Add", "MstEmployee")', null, "Add Emloyee");
            });

            // event detail data
            $("#list-data").on("click", ".btn-detail", function () {
                // mendeklarasikan id yang dipilih
                var vId = $(this).val();
                // memanggil method ajaxModel diatas
                ajaxModal('@Url.Action("Detail","MstEmployee")', { id: vId }, "Add MstEmployee");
            });

            // event Edit data
            $("#list-data").on("click", ".btn-edit", function () {
                // mendeklarasikan id yang dipilih
                var vId = $(this).val();
                // memanggil method ajaxModel diatas
                ajaxModal('@Url.Action("Edit","MstEmployee")', { id: vId }, "Edit Data MstEmployee");
            });

            // event Delete data
            $("#list-data").on("click", ".btn-delete", function () {
                // mendeklarasikan id yang dipilih
                var vId = $(this).val();
                // memanggil method ajaxModel diatas
                ajaxModal('@Url.Action("Delete","MstEmployee")', { id: vId }, "Edit Data MstEmployee");
            });

            // event form submit
            $("#modal-form").on("submit", "#form-employee", function () {
                var action = $(this).attr('action');
                var formData = $(this).serialize();
                $.ajax({
                    url: action,
                    type: 'post',
                    dataType: 'json',
                    data: formData,
                    success: function (result) {
                        if (result.success) {
                            // menyembunyikan modal
                            $("#modal-form").modal("hide");
                            // memanggil method load data
                            loadData();
                        } else {
                            $(".modal-body").html(rdata);
                            $("#modal-form").modal("show");
                        }
                    }
                });
                return false;
            });
        });

    </script>
}

POS/POS.Web/Views/MstEmployee/_Add.cshtml
@model POS.ViewModel.MstEmployeeViewModel

@using (Html.BeginForm("Add", "MstEmployee", FormMethod.Post, new { @id = "form-mst-employee" }))
{
    <div class="box box-info">
        <div class="box-header">
           
        </div>
        <div class="box-body">
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    <div class="col-md-3">
                        @Html.EditorFor(model => model.first_name, new { htmlAttributes = new { @class = "form-control", @placeholder = "First Name" } })
                        @Html.ValidationMessageFor(model => model.first_name, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-md-3">
                        @Html.EditorFor(model => model.last_name, new { htmlAttributes = new { @class = "form-control", @placeholder = "Last Name" } })
                        @Html.ValidationMessageFor(model => model.last_name, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-md-3">
                        @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control", @placeholder = "Email" } })
                        @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-md-3">
                        @Html.DropDownList("Gender", new List<SelectListItem>
                   {
                             new SelectListItem{ Text="Mr.", Value="Mr"},
                             new SelectListItem{ Text="Ms.", Value="Ms"}
                    }, "Title"
                )
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-2">
                        <div class="box-tools">

                            <button id="btn-add-outlet" type="button" class="btn btn-primary">Assign Outlet</button>
                        </div>
                    </div>

                   
                    <div class="col-md-4">
                        <label for="chkAccount">
                            <input type="checkbox" id="chkAccount" />
                            Create Account?
                        </label>
                    </div>

                </div>

                <div class="form-group" id="dvRole" style="display:none;">
                    <hr />
                    <div class="col-md-3">
                        @Html.DropDownListFor(model => model.id, (IEnumerable<SelectListItem>)ViewBag.listRole, "= Pilih Role =", new { @class = "form-control" })
                    </div>
                   
                    <div class="col-md-3">
                        @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control", @placeholder = "Username" } })
                        @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-md-3">
                        @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control", @placeholder = "Password" } })
                        @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
                    </div>
                </div>
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>Outlet ID</th>
                            <th>Outlet Name</th>
                        </tr>
                    </thead>
                    <tbody id="list-outlet">

                    </tbody>
                </table>

                <div class="form-group">
                   
                    <button id="btn-save" type="button" class="btn btn-primary pull-right">Save</button>
                    
                    <button id="btn-cancle" type="button" class="btn btn-primary pull-right">Cancle</button>

                </div>

            </div>
        </div>
    </div>
}

POS/POS.Web/Views/MstEmployee/_AddOutlet.cshtml
@model POS.ViewModel.EmployeeOutletViewModel

<div class="form-horizontal">
    <div class="form-group">
        @Html.LabelFor(model => model.outlet_id, htmlAttributes: new { @class = "control-label col-md-4" })
        <div class="col-md-7">
            @Html.DropDownListFor(model => model.outlet_id, (IEnumerable<SelectListItem>)ViewBag.ListOutlet, "=Pilih Outlet=", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.outlet_id, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">
            Cancel
        </button>
        <button type="button" class="btn btn-primary pull-right" id="btn-pilih-outlet">
            Add
        </button>
    </div>
</div>

POS/POS.Web/Views/MstEmployee/_List.cshtml
@model IEnumerable<POS.ViewModel.MstEmployeeViewModel>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.first_name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.last_name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.have_account)
        </th>
       
        <th>
            @Html.DisplayNameFor(model => model.active)
        </th>
        <th>
            Action
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.first_name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.last_name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.have_account)
        </td>
       
        <td>
            @Html.DisplayFor(modelItem => item.active)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.id }) |
            @Html.ActionLink("Details", "Details", new { id=item.id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.id })
        </td>
    </tr>
}

</table>