POS/POS.Web/Controllers/AjaxController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using POS.Repo;

namespace POS.Web.Controllers
{
    public class AjaxController : Controller
    {
        // GET: Ajax
        public JsonResult GetProvince()
        {
            return Json(MstProvinceRepo.Get(), JsonRequestBehavior.AllowGet);
        }


        public JsonResult GetRegion(int provinceId)
        {
            return Json(MstRegionRepo.GetByProvinsi(provinceId), JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetDistrict(int regionId)
        {
            return Json(MstDistrictRepo.GetByRegion(regionId), JsonRequestBehavior.AllowGet);
        }
    }
}

POS/POS.Web/Controllers/MstCustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using POS.Repo;
using POS.ViewModel;


namespace POS.Web.Controllers
{
    // edit
    public class MstCustomerController : Controller
    {
        // GET: Customer
        public ActionResult Index()
        {
            return View(MstCustomerRepo.Get());
        }

        public ActionResult List()
        {
            return PartialView("_List", MstCustomerRepo.Get());
        }

        // search
        public ActionResult Search(string keySearch)
        {
            return PartialView("_List", MstCustomerRepo.Get(keySearch));
        }

        public ActionResult Add()
        {
            ViewBag.ListProvince = new SelectList(MstProvinceRepo.Get(), "id", "name");
            ViewBag.ListRegion = new SelectList(String.Empty, "", "");
            ViewBag.ListDistrict = new SelectList(String.Empty, "", "");
            return PartialView("_Add");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(MstCustomerViewModel model)
        {
            if (ModelState.IsValid)
            {
                if (MstCustomerRepo.Insert(model))
                {
                    return Json(new
                    {
                        success = true,
                        message = "Simpan Berhasil"
                    });
                }
                else
                {
                    return Json(new
                    {
                        success = false,
                        message = "Simpan Gagal"
                    });
                }
            }
            ViewBag.ListProvince = new SelectList(MstProvinceRepo.Get(), "id", "name");
            ViewBag.ListRegion = new SelectList(String.Empty, "", "");
            ViewBag.ListDistrict = new SelectList(String.Empty, "", "");
            return PartialView("_Add", model);
        }

        public ActionResult Edit(int id)
        {
            ViewBag.ListProvince = new SelectList(MstProvinceRepo.Get(), "id", "name");
            ViewBag.ListRegion = new SelectList(MstRegionRepo.Get(), "id", "name");
            ViewBag.ListDistrict = new SelectList(MstDistrictRepo.Get(), "id", "name");
            return PartialView("_Edit", MstCustomerRepo .Get(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(MstCustomerViewModel model)
        {
            if (ModelState.IsValid)
            {
                if (MstCustomerRepo.Update(model))
                {
                    return Json(new
                    {
                        success = true,
                        message = "Simpan Berhasil"
                    });
                }
                else
                {
                    return Json(new
                    {
                        success = false,
                        message = "Simpan Gagal"
                    });
                }
            }
            ViewBag.ListProvince = new SelectList(MstProvinceRepo.Get(), "id", "name");
            ViewBag.ListRegion = new SelectList(MstRegionRepo.Get(), "id", "name");
            ViewBag.ListDistrict = new SelectList(MstDistrictRepo.Get(), "id", "name");
            return PartialView("_Edit", model);
        }

        public ActionResult Detail(int id)

        {
            MstCustomerViewModel data = MstCustomerRepo.Get(id);
            return PartialView("_Detail", data);
        }

        public JsonResult Delete(int id)
        {
            if (MstCustomerRepo.Delete(id))
            {
                return Json(new
                    {
                        success = true,
                        message = "Simpan Berhasil"
                    }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new
                {
                    success = false,
                    message = "Simpan Gagal"
                }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(MstCustomerViewModel model)
        {
            if (ModelState.IsValid)
            {
                if (MstCustomerRepo.Delete(model))
                {
                    return Json(new
                    {
                        success = true,
                        message = "Simpan Berhasil"
                    });
                }
                else
                {
                    return Json(new
                    {
                        success = false,
                        message = "Simpan Gagal"
                    });
                }
            }
            return PartialView("_Delete", model);
        }
    }
}

POS/POS.Web/Views/MstCustomer/Index.cshtml
@model IEnumerable<POS.ViewModel.MstCustomerViewModel>
@{
    ViewBag.Title = "Index";
}

<div class="box box-info">
    <div class="box-header">
        <h3 class="box-title">Customer</h3>

        <div class="box-tools">
            <div class="input-group input-group-sm" style="width: 250px;">
                <input type="text" id="txt-search" name="txt-search" class="form-control pull-right" placeholder="Search">
                <div class="input-group-btn">
                    <button type="button" id="btn-search" class="btn btn-default"><i class="fa fa-search"></i></button>
                    <button type="button" class="btn btn-info" id="btn-add"><i class="fa fa-plus"></i> &nbsp;Create</button>
                </div>
            </div>
        </div>

    </div>
    <div class="box-body">
        <table class="table">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.name)
                    </th>
                    <th>
                        Phone
                    </th>
                    <th>
                        Email
                    </th>
                </tr>
            </thead>
            <tbody id="list-data">
                @Html.Partial("_List", Model)
            </tbody>
        </table>
    </div>
</div>

<!-- modals JQuery-->
<div class="modal fade" tabindex="-1" role="dialog" id="modal-form">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Modal title</h4>
            </div>
            <div class="modal-body">
                <p>One fine body&hellip;</p>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<!-- memanggil btn-add pada tombol Add di atas dg modals-->
@section Scripts{
    <script type="text/javascript">

        //datepicker
        $(".datepicker").datepicker({
            autoClose:true,
        });

        function ajaxModal(vUrl, vData, vTitle) {
            $.ajax({
                url: vUrl,
                data: vData,
                type: 'get',
                dataType: 'html',
                success: function (result) {
                    $(".modal-title").html(vTitle);
                    $(".modal-body").html(result);
                    $("#modal-form").modal("show");
                }
            });
        }
        $(document).ready(function () {
            function loadData(url, data) {
                $.ajax({
                    url: url,
                    data: data,
                    type: 'get',
                    dataType: 'html',
                    success: function (data) {
                        $("#list-data").html(data);
                    }
                });
            }

            // show form add
            $("#btn-add").on("click", function () {
                var url = '@Url.Action("Add", "MstCustomer")';
                ajaxModal(url, '', "Add Customer");
            });

            // search
            $("#btn-search").on("click", function () {
                var url = '@Url.Action("Search", "MstCustomer")';
                var data = { keySearch: $('#txt-search').val() };
                loadData(url, data);
            });

            $("#txt-search").keypress(function (e) {
                if (e.which == 13) {
                    var url = '@Url.Action("Search", "MstCustomer")';
                    var data = { keySearch: $('#txt-search').val() };
                    loadData(url, data);
                }
               
            });
           

            // edit
            $("#list-data").on("click", ".btn-edit", function () {
                var vId = $(this).val();
                var url = '@Url.Action("Edit", "MstCustomer")';
                ajaxModal(url, { id: vId }, "Ubah Customer");
            });

            // detail
            $("#list-data").on("click", ".btn-detail", function () {
                // mendeklarasikan ID yang dipilih
                var vId = $(this).val();
                var url = '@Url.Action("Detail", "MstCustomer")';
                ajaxModal(url, { id: vId }, "Detail Customer");
            });

            // delete
            $("#modal-form").on("click", "#btn-delete", function () {
                // mengambil ID dari tombol btn-edit (val = value) yang ada di value
                var vId = $(this).val();
                var url = '@Url.Action("Delete", "MstCustomer")';
                $.ajax({
                    url: url,
                    type: 'get',
                    dataType: 'json',
                    data: { id: vId },
                    success: function (rdata) {
                        if (rdata.success) {
                            $("#modal-form").modal("hide");
                            loadData('@Url.Action("List", "MstCustomer")', null);
                        } else {
                            $(".modal-body").html(rdata);
                            $("#modal-form").modal("show");
                        }
                    }
                });
            });

            // save add data
            $("#modal-form").on("submit", "#form-mst-Customer", function () {
                
                // menyimpan data
                var action = $(this).attr('action'); // data nya mau diarahkan ke mana?
                var formData = $(this).serialize();
                $.ajax({
                    url: action,
                    type: 'post',
                    dataType: 'json',
                    data: formData,
                    success: function (rdata) {
                        if (rdata.success) {
                            $("#modal-form").modal("hide");
                            loadData('@Url.Action("List", "MstCustomer")', null);
                        } else {
                            $(".modal-body").html(rdata);
                            $("#modal-form").modal("show");
                        }
                    }
                });
                // agar tidak re-direct maka berikan return false
                return false;
            });

            

            //provinsi di pilih
            $("#modal-form").on("change", "#province_id", function () {
                var vId = $(this).val();
                $.ajax({
                    url: '@Url.Action("GetRegion", "Ajax")',
                    data: { provinceId: vId },
                    type: 'get',
                    dataType: 'json',
                    success: function (result) {
                        $("#modal-form").find("#region_id").empty();
                        $("#modal-form").find("#region_id").append('<option>-- Pilih Kota --</option>');
                        $.each(result, function (index, item) {
                            $("#modal-form").find("#region_id").append('<option value="' + item.id + '">' + item.name + '</option>');
                        });
                    }
                });
            });
            // pilih kecamatan
            $("#modal-form").on("change", "#region_id", function () {
                var vId = $(this).val();
                $.ajax({
                    url: '@Url.Action("GetDistrict", "Ajax")',
                    data: { regionId: vId },
                    type: 'get',
                    dataType: 'json',
                    success: function (result) {
                        $("#modal-form").find("#district_id").empty();
                        $("#modal-form").find("#district_id").append('<option>-- Pilih Kecamatan --</option>');
                        $.each(result, function (index, item) {
                            $("#modal-form").find("#district_id").append('<option value="' + item.id + '">' + item.name + '</option>');
                        });
                    }
                });
            });
        });
    </script>
}

POS/POS.Web/Views/MstCustomer/_Add.cshtml
@model POS.ViewModel.MstCustomerViewModel
<link href="~/Content/plugins/datepicker/datepicker3.css" rel="stylesheet" />
@using (Html.BeginForm("Add", "MstCustomer", FormMethod.Post, new { @id = "form-mst-Customer" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <!-- @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" }) -->
            <div class="col-md-12">
                @Html.TextBoxFor(model => model.name, new { @class = "form-control", @placeholder="Name"})
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <!-- @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" }) -->
            <div class="col-md-12">
                @Html.TextBoxFor(model => model.email, new { @class = "form-control", @placeholder = "Email" })
                @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <!-- @Html.LabelFor(model => model.phone , htmlAttributes: new { @class = "control-label col-md-2" }) -->
            <div class="col-md-12">
                @Html.TextBoxFor(model => model.phone , new { @class = "form-control", @placeholder = "Phone Number" })
                @Html.ValidationMessageFor(model => model.phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <!-- @Html.LabelFor(model => model.dob  , htmlAttributes: new { @class = "control-label col-md-2" }) -->
            <div class="col-md-12">
                @Html.TextBoxFor(model => model.dob, new { @class = "form-control datepicker", @placeholder = "Date Of Birth" })
                @Html.ValidationMessageFor(model => model.dob, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <!-- @Html.LabelFor(model => model.address  , htmlAttributes: new { @class = "control-label col-md-2" }) -->
            <div class="col-md-12">
                @Html.TextBoxFor(model => model.address, new { @class = "form-control", @placeholder = "Address" })
                @Html.ValidationMessageFor(model => model.address, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-4">
                @Html.DropDownListFor(model => model.province_id, (IEnumerable<SelectListItem>)ViewBag.ListProvince, "Province", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.province_id, "", new { @class = "text-danger" })
            </div>

            <div class="col-md-4">
                @Html.DropDownListFor(model => model.region_id, (IEnumerable<SelectListItem>)ViewBag.ListRegion, "Region", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.region_id, "", new { @class = "text-danger" })
            </div>

            <div class="col-md-4">
                @Html.DropDownListFor(model => model.district_id, (IEnumerable<SelectListItem>)ViewBag.ListDistrict, "District", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.district_id, "", new { @class = "text-danger" })
            </div>


        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-default  pull-left" data-dismiss="modal">Cancel</button>
            <button type="submit" class="btn btn-primary">
                Save
            </button>
        </div>
    </div>
}
<script src="~/Scripts/plugins/datepicker/bootstrap-datepicker.js"></script>
<script>
    $(function () {
        $(".datepicker").datepicker({
            autoclose: true,
            format:"dd/MM/yyyy"
        });
    });
</script>

POS/POS.Web/Views/MstCustomer/_Detail.cshtml
@model POS.ViewModel.MstCustomerViewModel

<div>
    <h4>MstCustomerViewModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dob)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dob)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.namaProvinsi )
        </dt>

        <dd>
            @Html.DisplayFor(model => model.namaProvinsi )
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.namaKota)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.namaKota )
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.namaKecamatan )
        </dt>

        <dd>
            @Html.DisplayFor(model => model.namaKecamatan )
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.created_by)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.created_by)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.created_on)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.created_on)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.modified_by)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.modified_by)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.modified_on)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.modified_on)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.active)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.active)
        </dd>

    </dl>
</div>

POS/POS.Web/Views/MstCustomer/_Edit.cshtml
@model POS.ViewModel.MstCustomerViewModel
<link href="~/Content/plugins/datepicker/datepicker3.css" rel="stylesheet" />
@using (Html.BeginForm("Edit", "MstCustomer", FormMethod.Post, new { @id = "form-mst-Customer" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.dob, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dob, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.dob, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-4">
                @Html.DropDownListFor(model => model.province_id, (IEnumerable<SelectListItem>)ViewBag.ListProvince, "Province", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.province_id, "", new { @class = "text-danger" })
            </div>

            <div class="col-md-4">
                @Html.DropDownListFor(model => model.region_id, (IEnumerable<SelectListItem>)ViewBag.ListRegion, "Region", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.region_id, "", new { @class = "text-danger" })
            </div>

            <div class="col-md-4">
                @Html.DropDownListFor(model => model.district_id, (IEnumerable<SelectListItem>)ViewBag.ListDistrict, "District", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.district_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class=" col-md-12">
                <button type="submit" class="btn btn-primary pull-right">Save</button>
            </div>
           
        </div>
    </div>
}

<script src="~/Scripts/plugins/datepicker/bootstrap-datepicker.js"></script>
<script>
    $(function () {
        $(".datepicker").datepicker({
            autoclose: true,
            format:"yyyy-mm-dd"
        });
    });
</script>

POS/POS.Web/Views/MstCustomer/_List.cshtml
@model IEnumerable<POS.ViewModel.MstCustomerViewModel>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.phone)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.email)
        </td>
        <td>
            <button class="btn btn-warning btn-xs btn-edit" value="@item.id"><i class="fa fa-edit"></i> Edit</button>
            <button class="btn btn-success btn-xs btn-detail" value="@item.id"><i class="fa fa-eye"></i> View</button>
        </td>
    </tr>
}